clc
close all
clear all

% Description:
% This script corresponds to Analysis Z - The correlation between rs-Fc patterns and ODC maps (Figure 8)
% An rm ANOVA is computed to assess the effects of H1, shifted H0 or rotated H0.
% Authors: Marianna E. Schmidt (marianna.schmidt@maxplanckschools.de), Iman Aganj, Shahin Nasr

%% Specifications

% donut radii
distEdgeRange = 4:0.5:10;

% Define the base directory where the subject folders are stored
baseDirectory = '/space/ardebil/1/users/Others/Marianna/FC_7T_Coronal/Controls/Results';
% subjects
subNames = {'myla','aman', 'ylri', 'auil', 'arak', 'aroo', 'atib', 'imyy', 'chss', 'evad', 'haas', 'rcgr'};
layers = {'0-2', '4-6', '8-10'};

%% Load data (shifted version)

% Initialize cell array to store meanAbsR for each subject
meanAbsRAll = zeros(length(subNames),length(layers),length(distEdgeRange),2,2);

for n = 1:length(subNames)
    for l = 1:length(layers)
        subjectDir = fullfile(baseDirectory, ['V1_layers_' layers{l} '_intrahemispheric'], subNames{n});
        matFilePath = fullfile(subjectDir, 'meanAbsR_Denoised_excl_3mm.mat');
        data = load(matFilePath, 'meanAbsR');
        meanAbsRAll(n,l,:,:,:) = data.meanAbsR;
    end
end

%% ANOVA (for shifted version)

% meanAbsRAll size: subjects, layers, distances, H1 H0, hemis
% mean over hemis
meanAbsRAll_mean = mean(meanAbsRAll,5);

STATS = [
  meanAbsRAll_mean(:,1,1,1) meanAbsRAll_mean(:,2,1,1) meanAbsRAll_mean(:,1,1,1) ...
  meanAbsRAll_mean(:,1,2,1) meanAbsRAll_mean(:,2,2,1) meanAbsRAll_mean(:,1,2,1) ...
  meanAbsRAll_mean(:,1,3,1) meanAbsRAll_mean(:,2,3,1) meanAbsRAll_mean(:,1,3,1) ...
  meanAbsRAll_mean(:,1,4,1) meanAbsRAll_mean(:,2,4,1) meanAbsRAll_mean(:,1,4,1) ...
  meanAbsRAll_mean(:,1,5,1) meanAbsRAll_mean(:,2,5,1) meanAbsRAll_mean(:,1,5,1) ...
  meanAbsRAll_mean(:,1,6,1) meanAbsRAll_mean(:,2,6,1) meanAbsRAll_mean(:,1,6,1) ...
  meanAbsRAll_mean(:,1,7,1) meanAbsRAll_mean(:,2,7,1) meanAbsRAll_mean(:,1,7,1) ...
  meanAbsRAll_mean(:,1,8,1) meanAbsRAll_mean(:,2,8,1) meanAbsRAll_mean(:,1,8,1) ...
  meanAbsRAll_mean(:,1,9,1) meanAbsRAll_mean(:,2,9,1) meanAbsRAll_mean(:,1,9,1) ...
  meanAbsRAll_mean(:,1,10,1) meanAbsRAll_mean(:,2,10,1) meanAbsRAll_mean(:,1,10,1) ...
  meanAbsRAll_mean(:,1,11,1) meanAbsRAll_mean(:,2,11,1) meanAbsRAll_mean(:,1,11,1) ...
  meanAbsRAll_mean(:,1,12,1) meanAbsRAll_mean(:,2,12,1) meanAbsRAll_mean(:,1,12,1) ...
  meanAbsRAll_mean(:,1,13,1) meanAbsRAll_mean(:,2,13,1) meanAbsRAll_mean(:,1,13,1) ...
  meanAbsRAll_mean(:,1,1,2) meanAbsRAll_mean(:,2,1,2) meanAbsRAll_mean(:,1,1,2) ...
  meanAbsRAll_mean(:,1,2,2) meanAbsRAll_mean(:,2,2,2) meanAbsRAll_mean(:,1,2,2) ...
  meanAbsRAll_mean(:,1,3,2) meanAbsRAll_mean(:,2,3,2) meanAbsRAll_mean(:,1,3,2) ...
  meanAbsRAll_mean(:,1,4,2) meanAbsRAll_mean(:,2,4,2) meanAbsRAll_mean(:,1,4,2) ...
  meanAbsRAll_mean(:,1,5,2) meanAbsRAll_mean(:,2,5,2) meanAbsRAll_mean(:,1,5,2) ...
  meanAbsRAll_mean(:,1,6,2) meanAbsRAll_mean(:,2,6,2) meanAbsRAll_mean(:,1,6,2) ...
  meanAbsRAll_mean(:,1,7,2) meanAbsRAll_mean(:,2,7,2) meanAbsRAll_mean(:,1,7,2) ...
  meanAbsRAll_mean(:,1,8,2) meanAbsRAll_mean(:,2,8,2) meanAbsRAll_mean(:,1,8,2) ...
  meanAbsRAll_mean(:,1,9,2) meanAbsRAll_mean(:,2,9,2) meanAbsRAll_mean(:,1,9,2) ...
  meanAbsRAll_mean(:,1,10,2) meanAbsRAll_mean(:,2,10,2) meanAbsRAll_mean(:,1,10,2) ...
  meanAbsRAll_mean(:,1,11,2) meanAbsRAll_mean(:,2,11,2) meanAbsRAll_mean(:,1,11,2) ...
  meanAbsRAll_mean(:,1,12,2) meanAbsRAll_mean(:,2,12,2) meanAbsRAll_mean(:,1,12,2) ...
  meanAbsRAll_mean(:,1,13,2) meanAbsRAll_mean(:,2,13,2) meanAbsRAll_mean(:,1,13,2) ...
  ];

ts = arrayfun(@(x) sprintf('t%d', x), 1:78, 'UniformOutput', false);

t =array2table(STATS,'VariableNames', ts);

within = table(...
    repmat({'A'; 'B'; 'C'}, 26, 1), ... % effect of layer
    repmat({'AA'; 'AA'; 'AA'; 'BB'; 'BB'; 'BB'; 'CC'; 'CC'; 'CC'; ...
    'DD'; 'DD'; 'DD'; 'EE'; 'EE'; 'EE'; 'FF'; 'FF'; 'FF'; ...
    'GG'; 'GG'; 'GG'; 'HH'; 'HH'; 'HH'; 'II'; 'II'; 'II'; ...
    'JJ'; 'JJ'; 'JJ'; 'KK'; 'KK'; 'KK'; 'LL'; 'LL'; 'LL'; ...
    'MM'; 'MM'; 'MM'}, 2, 1), ... % effect of donut radius
    [repmat({'AAA'}, 39, 1); repmat({'BBB'}, 39, 1)], ... % effect of measurement type
    'VariableNames', {'Layer', 'Radius', 'Type'});

rm = fitrm(t,'t1-t78~1','WithinDesign',within)
disp('Comparison radius & layer & type for shifted H0')
ranovatbl = ranova(rm,'WithinModel','Layer+Radius+Type+Layer*Type+Layer*Radius+Radius*Layer+Radius*Type+Radius*Type*Layer')

%%

close all
clear all

%% Specifications

% donut radii
distEdgeRange = 4:0.5:10;

% Define the base directory where the subject folders are stored
baseDirectory = '/space/ardebil/1/users/Others/Marianna/FC_7T_Coronal/Controls/Results';
% subjects
subNames = {'myla','aman', 'ylri', 'auil', 'arak', 'aroo', 'atib', 'imyy', 'chss', 'evad', 'haas', 'rcgr'};
layers = {'0-2', '4-6', '8-10'};

%% Load data (rotated version)

% Initialize cell array to store meanAbsR for each subject
meanAbsRAll = zeros(length(subNames),length(layers),length(distEdgeRange),2,2);

for n = 1:length(subNames)
    for l = 1:length(layers)
        subjectDir = fullfile(baseDirectory, ['V1_layers_' layers{l} '_intrahemispheric'], subNames{n});
        matFilePath = fullfile(subjectDir, 'meanAbsR_Denoised_excl_3mm_rotated.mat');
        data = load(matFilePath, 'meanAbsR');
        meanAbsRAll(n,l,:,:,:) = data.meanAbsR;
    end
end

%% ANOVA (for shifted version)

% meanAbsRAll size: subjects, layers, distances, H1 H0, hemis
% mean over hemis
meanAbsRAll_mean = mean(meanAbsRAll,5);

STATS = [
  meanAbsRAll_mean(:,1,1,1) meanAbsRAll_mean(:,2,1,1) meanAbsRAll_mean(:,1,1,1) ...
  meanAbsRAll_mean(:,1,2,1) meanAbsRAll_mean(:,2,2,1) meanAbsRAll_mean(:,1,2,1) ...
  meanAbsRAll_mean(:,1,3,1) meanAbsRAll_mean(:,2,3,1) meanAbsRAll_mean(:,1,3,1) ...
  meanAbsRAll_mean(:,1,4,1) meanAbsRAll_mean(:,2,4,1) meanAbsRAll_mean(:,1,4,1) ...
  meanAbsRAll_mean(:,1,5,1) meanAbsRAll_mean(:,2,5,1) meanAbsRAll_mean(:,1,5,1) ...
  meanAbsRAll_mean(:,1,6,1) meanAbsRAll_mean(:,2,6,1) meanAbsRAll_mean(:,1,6,1) ...
  meanAbsRAll_mean(:,1,7,1) meanAbsRAll_mean(:,2,7,1) meanAbsRAll_mean(:,1,7,1) ...
  meanAbsRAll_mean(:,1,8,1) meanAbsRAll_mean(:,2,8,1) meanAbsRAll_mean(:,1,8,1) ...
  meanAbsRAll_mean(:,1,9,1) meanAbsRAll_mean(:,2,9,1) meanAbsRAll_mean(:,1,9,1) ...
  meanAbsRAll_mean(:,1,10,1) meanAbsRAll_mean(:,2,10,1) meanAbsRAll_mean(:,1,10,1) ...
  meanAbsRAll_mean(:,1,11,1) meanAbsRAll_mean(:,2,11,1) meanAbsRAll_mean(:,1,11,1) ...
  meanAbsRAll_mean(:,1,12,1) meanAbsRAll_mean(:,2,12,1) meanAbsRAll_mean(:,1,12,1) ...
  meanAbsRAll_mean(:,1,13,1) meanAbsRAll_mean(:,2,13,1) meanAbsRAll_mean(:,1,13,1) ...
  meanAbsRAll_mean(:,1,1,2) meanAbsRAll_mean(:,2,1,2) meanAbsRAll_mean(:,1,1,2) ...
  meanAbsRAll_mean(:,1,2,2) meanAbsRAll_mean(:,2,2,2) meanAbsRAll_mean(:,1,2,2) ...
  meanAbsRAll_mean(:,1,3,2) meanAbsRAll_mean(:,2,3,2) meanAbsRAll_mean(:,1,3,2) ...
  meanAbsRAll_mean(:,1,4,2) meanAbsRAll_mean(:,2,4,2) meanAbsRAll_mean(:,1,4,2) ...
  meanAbsRAll_mean(:,1,5,2) meanAbsRAll_mean(:,2,5,2) meanAbsRAll_mean(:,1,5,2) ...
  meanAbsRAll_mean(:,1,6,2) meanAbsRAll_mean(:,2,6,2) meanAbsRAll_mean(:,1,6,2) ...
  meanAbsRAll_mean(:,1,7,2) meanAbsRAll_mean(:,2,7,2) meanAbsRAll_mean(:,1,7,2) ...
  meanAbsRAll_mean(:,1,8,2) meanAbsRAll_mean(:,2,8,2) meanAbsRAll_mean(:,1,8,2) ...
  meanAbsRAll_mean(:,1,9,2) meanAbsRAll_mean(:,2,9,2) meanAbsRAll_mean(:,1,9,2) ...
  meanAbsRAll_mean(:,1,10,2) meanAbsRAll_mean(:,2,10,2) meanAbsRAll_mean(:,1,10,2) ...
  meanAbsRAll_mean(:,1,11,2) meanAbsRAll_mean(:,2,11,2) meanAbsRAll_mean(:,1,11,2) ...
  meanAbsRAll_mean(:,1,12,2) meanAbsRAll_mean(:,2,12,2) meanAbsRAll_mean(:,1,12,2) ...
  meanAbsRAll_mean(:,1,13,2) meanAbsRAll_mean(:,2,13,2) meanAbsRAll_mean(:,1,13,2) ...
  ];

ts = arrayfun(@(x) sprintf('t%d', x), 1:78, 'UniformOutput', false);

t =array2table(STATS,'VariableNames', ts);

within = table(...
    repmat({'A'; 'B'; 'C'}, 26, 1), ... % effect of layer
    repmat({'AA'; 'AA'; 'AA'; 'BB'; 'BB'; 'BB'; 'CC'; 'CC'; 'CC'; ...
    'DD'; 'DD'; 'DD'; 'EE'; 'EE'; 'EE'; 'FF'; 'FF'; 'FF'; ...
    'GG'; 'GG'; 'GG'; 'HH'; 'HH'; 'HH'; 'II'; 'II'; 'II'; ...
    'JJ'; 'JJ'; 'JJ'; 'KK'; 'KK'; 'KK'; 'LL'; 'LL'; 'LL'; ...
    'MM'; 'MM'; 'MM'}, 2, 1), ... % effect of donut radius
    [repmat({'AAA'}, 39, 1); repmat({'BBB'}, 39, 1)], ... % effect of measurement type
    'VariableNames', {'Layer', 'Radius', 'Type'});

rm = fitrm(t,'t1-t78~1','WithinDesign',within)
disp('Comparison radius & layer & type for rotated H0')
ranovatbl = ranova(rm,'WithinModel','Layer+Radius+Type+Layer*Type+Layer*Radius+Radius*Layer+Radius*Type+Radius*Type*Layer')
